name: braze_plugin_web
description: Unofficial Braze Plugin for Flutter for Web. It is mostly a Flutter Web Plugin acting as a wrapper around the official Braze Web SDK.
repository: https://github.com/jasper-health/braze_plugin_web_fork
version: 0.1.6

environment:
  sdk: ">=2.17.6 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # JavaScript Interop
  js: ^0.6.5

flutter:
  plugin:
    platforms:
      web:
        pluginClass: BrazePluginWeb
        fileName: src/braze_plugin_web.dart
